"""Storage protocol. All DB access in the app goes through this interface.

Exists primarily to make ``tests/unit/`` fakeable without disk I/O. Only one
real implementation today (``SqliteStorage``); if we ever add a second, the
protocol keeps the swap honest.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

import pandas as pd

from startup_radar.models import JobMatch, Startup


class Storage(Protocol):
    # --- schema ---
    def migrate_to_latest(self) -> list[int]: ...
    def user_version(self) -> int: ...
    def close(self) -> None: ...

    # --- reads: startups / jobs ---
    def get_all_startups(self) -> pd.DataFrame: ...
    def get_all_job_matches(self) -> pd.DataFrame: ...
    def get_existing_companies(self) -> set[str]: ...
    def get_rejected_companies(self) -> set[str]: ...
    def get_existing_job_keys(self) -> set[str]: ...

    # --- writes: startups / jobs ---
    def insert_startups(self, startups: list[Startup | dict]) -> int: ...
    def insert_job_matches(self, jobs: list[JobMatch | dict]) -> int: ...
    def update_startup_website(self, company_name: str, website: str) -> None: ...
    def update_startup_status(self, company_name: str, status: str) -> None: ...
    def update_job_status(self, company_name: str, role_title: str, status: str) -> None: ...
    def update_job_notes(self, company_name: str, role_title: str, notes: str) -> None: ...
    def delete_startup(self, company_name: str) -> None: ...
    def delete_job_match(self, company_name: str, role_title: str) -> None: ...

    # --- processed-items dedup (sources) ---
    def is_processed(self, source: str, item_id: str) -> bool: ...
    def mark_processed(self, source: str, item_ids: Iterable[str]) -> None: ...

    # --- activities / tracker ---
    def insert_activity(self, activity: dict) -> int: ...
    def get_activities(self, company_name: str | None = None) -> pd.DataFrame: ...
    def get_overdue_followups(self, today: str) -> pd.DataFrame: ...
    def get_tracker_status(self, company_name: str) -> dict: ...
    def upsert_tracker_status(
        self, company_name: str, status: str, role: str = "", notes: str = ""
    ) -> None: ...
    def get_all_tracker_statuses(self) -> dict: ...
    def delete_tracker_entry(self, company_name: str) -> None: ...
    def get_tracker_summary(self) -> pd.DataFrame: ...

    # --- connections (LinkedIn CSV) ---
    def import_connections(self, rows: list[dict]) -> int: ...
    def get_connections_count(self) -> int: ...
    def get_connections_last_uploaded(self) -> str: ...
    def search_connections_by_company(self, company_name: str) -> pd.DataFrame: ...
    def search_connections_by_companies(self, company_names: list[str]) -> pd.DataFrame: ...
    def hide_intro(self, connection_url: str, company_name: str) -> None: ...
    def get_hidden_intros(self, company_name: str) -> set[str]: ...

    # --- runs / telemetry (Phase 11) ---
    def record_run(
        self,
        source: str,
        *,
        started_at: str,
        ended_at: str,
        items_fetched: int,
        items_kept: int,
        error: str | None,
        user_version_at_run: int,
    ) -> int: ...
    def last_run(self, source: str) -> dict | None: ...
    def failure_streak(self, source: str) -> int: ...
